using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace apapi.Models
{
    public class Quote
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string title { get; set; }
        public string description { get; set; } = string.Empty;
        public string source {get; set;}
        public string author {get; set;}

        
    }
}
