using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace apapi.Models
{
    public class Todo
    {
        
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        // standard BSonId generated by MongoDb
        public string InternalId { get; set; }
        public string title { get; set; }
        public bool complete { get; set; }
        public string description { get; set; } = string.Empty;

        public string createDate {get;set;}
    }
}
